SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL AND GENDER = 'W'
GROUP BY DATE_OF_BIRTH
HAVING MONTH(DATE_OF_BIRTH) = '03'
ORDER BY MEMBER_ID